name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    # Clean NuGet cache to avoid corruption issues
    - name: Clean NuGet cache
      run: dotnet nuget locals all --clear
    
    # Install MGCB tool globally first (before local tools)
    - name: Install MGCB tool globally
      run: |
        dotnet tool install --global dotnet-mgcb --version 3.8.4
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
    
    # Set up isolated NuGet packages directory with unique temp path
    - name: Setup NuGet cache
      run: |
        TEMP_NUGET_DIR="/tmp/nuget-packages-${{ github.run_id }}"
        mkdir -p "$TEMP_NUGET_DIR"
        echo "NUGET_PACKAGES=$TEMP_NUGET_DIR" >> $GITHUB_ENV
    
    # Restore local tools with retry logic
    - name: Restore local tools (with retry)
      run: |
        if [ -f ".config/dotnet-tools.json" ]; then
          echo "Restoring local tools..."
          for i in {1..3}; do
            if dotnet tool restore --disable-parallel; then
              echo "Tool restore succeeded on attempt $i"
              break
            else
              echo "Tool restore failed on attempt $i, retrying..."
              sleep 5
              dotnet nuget locals all --clear
            fi
          done
        else
          echo "No local tools manifest found, skipping tool restore"
        fi
    
    # Restore project dependencies
    - name: Restore dependencies
      run: dotnet restore --disable-parallel --no-cache --verbosity normal
    
    - name: Build
      run: dotnet build --no-restore --verbosity minimal
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
