name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    # Clean NuGet cache to avoid corruption issues
    - name: Clean NuGet cache
      run: dotnet nuget locals all --clear
    
    # Install MGCB tool globally first
    - name: Install MGCB tool globally
      run: |
        dotnet tool install --global dotnet-mgcb --version 3.8.4
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
    
    # Set up isolated NuGet packages directory with unique temp path
    - name: Setup NuGet cache
      run: |
        TEMP_NUGET_DIR="/tmp/nuget-packages-${{ github.run_id }}"
        mkdir -p "$TEMP_NUGET_DIR"
        echo "NUGET_PACKAGES=$TEMP_NUGET_DIR" >> $GITHUB_ENV
    
    # Restore local tools once at solution level to avoid race conditions
    - name: Restore local tools (solution level)
      run: |
        if [ -f ".config/dotnet-tools.json" ]; then
          echo "Restoring local tools at solution level..."
          dotnet tool restore --disable-parallel
        else
          echo "No local tools manifest found, skipping tool restore"
        fi
    
    # Restore project dependencies with MSBuild parallelism disabled and skip tool restore
    - name: Restore dependencies
      run: |
        dotnet restore --disable-parallel --no-cache --verbosity normal \
          -p:RestoreDotnetTools=false \
          -maxcpucount:1
    
    - name: Build
      run: |
        dotnet build --no-restore --verbosity minimal \
          -p:RestoreDotnetTools=false \
          -maxcpucount:1
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
