name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install MGCB tool globally
      run: |
        dotnet tool install --global dotnet-mgcb --version 3.8.4
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Use isolated NuGet cache
      run: |
        mkdir -p ${{ github.workspace }}/.nuget/packages
        echo "NUGET_PACKAGES=${{ github.workspace }}/.nuget/packages" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore --disable-parallel

    - name: Build
      run: dotnet build --no-restore --verbosity minimal

    - name: Test
      run: dotnet test --no-build --verbosity normal
