name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # Use Windows for full MonoGame support
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Clean NuGet cache
      run: dotnet nuget locals all --clear
    
    - name: Install MGCB tool globally
      run: |
        dotnet tool install --global dotnet-mgcb --version 3.8.4
    
    - name: Restore local tools
      run: |
        if (Test-Path ".config/dotnet-tools.json") {
          dotnet tool restore --disable-parallel
        }
    
    - name: Restore dependencies
      run: |
        dotnet restore --disable-parallel --no-cache --verbosity normal -p:RestoreDotnetTools=false -maxcpucount:1
    
    - name: Build
      run: |
        dotnet build --no-restore --verbosity minimal -p:RestoreDotnetTools=false -maxcpucount:1
    
    - name: Test
      run: |
        $testProjects = Get-ChildItem -Recurse -Filter "*.Tests.csproj"
        if ($testProjects.Count -gt 0) {
          dotnet test --no-build --verbosity normal
        } else {
          Write-Host "No test projects found, skipping tests"
        }
